name: Deploy Storybook
on:
  push:
    branches: 
    - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkoutrepository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: Install packages
        run: npm i
      - name: Build project
        run: npm run storybook:build
      - name: Deploy to Firebase
        uses: lowply/deploy-firebase@v0.0.2
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_PROJECT: web-elements-260917
