name: CI
on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: web-elements
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: Install packages
        run: npm i
      - name: Build project
        run: npm run build
      - name: Publish to npm
        uses: JS-DevTools/npm-publish@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
